"""test migration

Revision ID: 4c3395f4e673
Revises: 8d8d2381a5bf
Create Date: 2025-05-16 20:39:20.726519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c3395f4e673'
down_revision = '8d8d2381a5bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sleep_record', schema=None) as batch_op:
        batch_op.alter_column('sleep_aid',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.create_unique_constraint('unique_user_date', ['user_id', 'date'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sleep_record', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_date', type_='unique')
        batch_op.alter_column('sleep_aid',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###