"""Your migration message

Revision ID: 96eece36810b
Revises: 398ad67def7b
Create Date: 2025-05-06 21:33:05.733636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96eece36810b'
down_revision = '398ad67def7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('achievement')
    op.drop_table('shared_profile')
    with op.batch_alter_table('sleep_goal', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('sleep_record', schema=None) as batch_op:
        batch_op.drop_column('disturbances')
        batch_op.drop_column('daytime_fatigue')
        batch_op.drop_column('sleep_aid')
        batch_op.drop_column('duration_minutes')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('timezone')
        batch_op.drop_column('location')
        batch_op.drop_column('bio')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('timezone', sa.VARCHAR(length=50), nullable=True))

    with op.batch_alter_table('sleep_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration_minutes', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('sleep_aid', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('daytime_fatigue', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('disturbances', sa.VARCHAR(length=20), nullable=True))

    with op.batch_alter_table('sleep_goal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))

    op.create_table('shared_profile',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('shared_with_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['shared_with_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('achievement',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('description', sa.VARCHAR(length=256), nullable=True),
    sa.Column('icon', sa.VARCHAR(length=64), nullable=True),
    sa.Column('unlocked', sa.BOOLEAN(), nullable=True),
    sa.Column('date_earned', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
