"""Add new fields and the Achievement model.

Revision ID: 9a87e4990a35
Revises: 96eece36810b
Create Date: 2025-05-07 16:09:36.534650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a87e4990a35'
down_revision = '96eece36810b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('achieved_at', sa.DateTime(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sleep_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sleep_disturbances', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('sleep_aid', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('daytime_dysfunction', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('caffeine', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('exercise', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('screen', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('eating', sa.Integer(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('timezone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('profile_pic', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_pic')
        batch_op.drop_column('bio')
        batch_op.drop_column('timezone')
        batch_op.drop_column('location')
        batch_op.drop_column('phone')

    with op.batch_alter_table('sleep_record', schema=None) as batch_op:
        batch_op.drop_column('eating')
        batch_op.drop_column('screen')
        batch_op.drop_column('exercise')
        batch_op.drop_column('caffeine')
        batch_op.drop_column('daytime_dysfunction')
        batch_op.drop_column('sleep_aid')
        batch_op.drop_column('sleep_disturbances')

    op.drop_table('achievement')
    # ### end Alembic commands ###
